ignouz/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django_summernote import urls as u
from application.views import *
from ckeditor_uploader import urls
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^ckeditor/', include(urls)),
    url(r'^summernote/',include(u)),
    url(r'^admin/', admin.site.urls),
    url(r'^$',index,name='Index'),
    url(r'^accounts/login/$',login,name='login'),
    url(r'^auth/$',auth_view,name='auth'),
    url(r'^accounts/logout/$',logout,name='logout'),
    url(r'^grade',grade,name='grade'),
    url(r'^community/comment/(?P<pk>\d+)',post_comment,name='post_comment'),
    url(r'^community/answer/(?P<pk>\d+)', ajax_answer, name='ajax_answer'),
    url(r'^result',result,name='result'),
    url(r'^accounts/registration/$',registration,name='registration'),
    url(r'^community/(?P<pk>.*)/', anss, name='answer'),
    url(r'^community/',community,name='community'),
    url(r'^answer/',answer,name='community'),
    url(r'^question_paper/$',question,name='question'),
    url(r'^question_paper/(?P<year>\d+)/(?P<month>\d+)/(?P<code>\d+)/$', question_paper, name='ques'),
    url(r'^question_paper/(?P<year>\d+)/(?P<month>\d+)/$',code_list,name='code_list'),

#    url(r'^question_paper/(?P<year>\d+)/(?P<month>\d+)/(?P<code>\d+)/$',question_paper, name='code_list'),
    url(r'^em',em,name='em'),
    #url('^test/',TemplateView.as_view(template_name='test.html'))
    url(r'^test/(?P<pk>.*)/',test,name='test')
]

application/forms.py
from django.contrib.auth.forms import AuthenticationForm,UserCreationForm
from django import forms
from django.contrib.auth import authenticate
from .models import *
from aloha.widgets import AlohaWidget
from ckeditor.widgets import CKEditorWidget
from django.contrib.auth.models import User
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget
class LoginForm(AuthenticationForm):
    username = forms.CharField(label="Username", max_length=30, widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'username'}))
    password = forms.CharField(label="Password", max_length=30, widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'password','type':'password'}))

    def clean(self,*args,**kwargs):
        username =self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        if username and password:
            user = authenticate(username=username,password=password)
            if not user:
                raise forms.ValidationError("this user doest not exist")
        return super(LoginForm,self).clean(*args,**kwargs)


class comment_form(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']

#class answerform(forms.Form):
#    ans = forms.CharField(max_length=20,widget=AlohaWidget)

class answerforms(forms.ModelForm):
    ans = forms.CharField(widget=CKEditorWidget())
    class Meta:
        model = Answer
        #widgets = SummernoteInplaceWidget
        fields = ['ans']

class Registrationform(UserCreationForm):
    first_name=forms.CharField(max_length=15)
    last_name=forms.CharField(max_length=15)
    email=forms.EmailField(error_messages={'required': 'already exist!'},widget=forms.TextInput(attrs={'type':"email",'class':"validate",'id':'email'}))
    #phone = forms.IntegerField()
    #phone = forms.IntegerField(widget=forms.TextInput(attrs={'type': "phone", 'class': "validate", 'id': 'phone','name':'phone'}))
    class Meta:
        model = User
        fields =("username","first_name","last_name","email")

    def clean(self,*args,**kwargs):
        ems=self.cleaned_data.get('email')
        u=self.cleaned_data.get('username')

        if User.objects.filter(username=u):
            raise forms.ValidationError("Username Already exist")
        if User.objects.filter(email=ems):
            raise forms.ValidationError("Email already exist")


        return self.cleaned_data




    def save(self,commit=True):
        user = super(Registrationform, self).save(commit=False)
        user.first_name = self.cleaned_data["first_name"]
        user.last_name=self.cleaned_data["last_name"]
        user.email = self.cleaned_data["email"]
        #user.get_profile
        #user.profile.phone = self.cleaned_data["phone"]
        if commit:
            user.save()
        return user

templates/answer.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} {{ question.qs }} - IGNOUZ{% endblock %}
{% block statics %}
<script src="{% static 'ckeditor/ckeditor.js' %}"></script>
<script src="{% static 'ckeditor/samples/js/sample.js' %}"></script>
<link rel="stylesheet" href="{% static 'ckeditor/samples/css/samples.css' %}">
<link rel="stylesheet" href="{% static 'ckeditor/samples/toolbarconfigurator/lib/codemirror/neo.css' %}">
<!--<link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">-->
{% endblock %}
{% include 'editor_file.html' %}

{% block content %}
    <div class="row">
        <ldiv class="container" style="position:relative;">
            <div class="row">
                <div class="col s12 m12 l12 icon-block">
                    <div class="section no-pad-bot card-panel " id="index-banner">
                    <div class="question">
                        <h5> {{ question.qs }}</h5>
                        <i> By {{ question.user }}</i>
                        <br>
                        <br>
                        <b>{{ answer.count }} Answers </b>
                    </div>
                        <hr>
                    <div class="answer-block">
                        {% for i in answer %}
                            <div class="answer no-style">

                                <p>{{ i.ans|safe }}</p>
                            <div class="right by">
                                <i >Answer by {{ i.user }}</i>
                                <i> on {{ i.date }}</i>
                            </div>
                            <div class="glyphicon-comment"><br>


                                <a href="javascript:myfunction({{ i.id }})" name="cmt" id="cmt">Comment</a>
                                <form id="post-comment">
                                <span id="cmt-ids" cmt-id="{{ i.id }}"></span>
                                    {% csrf_token %}
                                    <div id="comment-area" clicks="no">
                                        <div id="comment-form{{ i.id }}" clicks="no" class="comment-form" style="display: none;width: 40%">

                                        </div>
                                    </div>
                                </form>

                                <div class="comment-top nslide" id="nlide">
                                    <div class="comment-para">
                                        {% for j in comments %}
                                            {% if j.forwhat_id == i.id %}
                                                <p>{{ j.comment }} :- <i class="by">{{ j.user }} on {{ j.date }}</i></p>
                                                <hr width="100" size=".5px" color="grey" align="left">
                                            {% endif %}
                                        {% endfor %}
                                    </div>
                                 </div>
                            </div>
                            </div>
                            <br>
                            <hr>
                               {% endfor %}
                            <a id="ans" href="javascript:ed(1)">Give your answer</a>
                             <div class="giveyouranswer">
                                <div class="editor" id="editor">
                                    <form id="ans-form" ans_ids="{{ question.id }}">
                                        {% csrf_token %}
                                        {{ form.media }}
                                        {{ form.ans }}<br>
                                        <input type='submit' name='post-answer' value='submit'>
                                        <input type="button" class='btn' name='exm' value="submit" id='exm'>
                                   </form>
                                </div>
                             </div>
                             <div id="msg">
                                 
                             </div>
                        <br>
                    </div>
                </div>
            </div>
        </div>
    </ldiv>
    <style>



/*      h3 {
            font-size: 24px;

            line-height: 110%;
            margin: 1.14rem 0 0.912rem 0;
        }
        h4 {
            font-size: 1.78rem;
            line-height: 110%;
            margin: 1.14rem 0 0.912rem 0;
        }*/


        /*table.table td{
        border: dashed !important;
        border-width: thin !important;
        text-align: center;*/
        
            /*border: dashed !important;
        border-width: thin !important;
        height: auto !important;*/
        
        /*
        width: auto !important;
        white-space: nowrap;
        padding: 0;
        margin: 0;
        outline: 0;
        font-size: 100%;
        vertical-align: baseline;
        background: transparent;*/
    }

    .table{
        border-spacing: 0;
        background-color: transparent;
        border-collapse: collapse !important;
        width: 100% !important;
        max-width: 100%;
        margin-bottom: 20px;

    }

table > tbody > tr > td, .table > tbody > tr > th, .table > tfoot > tr > td, .table > tfoot > tr > th, .table > thead > tr > td, .table > thead > tr > th {
    width: auto!important;
    padding: 8px;
    line-height: 1.42857143;
    vertical-align: top;
    border-top: 1px solid #ddd;




        .giveyouranswer{
            margin-left: 15px;
            display: block;
            margin-right: 15px;
        }
        h1{
            font-size: 2em; !important;
        }
            h2 { font-size: 1.5em;  !important;}
        h3 { font-size: 1.17em;  !important; }
        h4 { font-size: 1.12em;  !important;}
        h5 { font-size: .83em;  !important;}
        h6 { font-size: .75em;  !important;}

        blockquote{
            font-style: italic;
            font-family: Georgia, Times, "Times New Roman", serif;
            padding: 2px 0;
            border-style: solid;

            border-width: 0;
            padding-left: 1.5rem;
            border-left: 5px solid #ccc;
        }


    


    </style>
{% endblock %}

{% block script %}




<script type="text/javascript">


$(document).on('click','#exm',function(e){
    //$('.editor').css('display: none;')
    $('#editor').toggle(200);
    $('#msg').html('<i>Thanks for your contribute</i>')
})

//$('.table').removeAttr("style")
$('.table').attr('style','');
$('.table').css('width', 'none');
console.log($('.table').val())

$(document).on('submit','#ans-form',function (e) {
    console.log('sdf '+$('#ans-form').attr('ans_ids')),
    console.log($('#ans-form').attr('ans_ids')),
    e.preventDefault(),
    $.ajax({
        type:'POST',
        url:'/community/answer/'+$('#ans-form').attr('ans_ids'),

        data:{
            ans:$('#id_ans').val(),
            csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
        },
        success:function (e) {
            if(e=='OK') {
                console.log('success')
                //$('.editor').css('display: block;');
            }
            else if(e=='NOT'){
                console.log('Not')
            }
            else{
                console.log('another error')
            }
        }
    })

});



function ed(e) {
    console.log('kjhkhk')
    //var ht="<div class='editor' id='first'>";
    //$('.ditor').html(ht);
    $('#editor').toggle(200);

    //initSample();
    //h="<input type='button' name='post-answer' value='submit'>"
    //$('.ans-submit').html(h)
}
function myfunction(e) {

    ht="<div id='areas'><textarea id='cmt-area' class='form-control' name='area1' cols='40' cmt-id=''></textarea><br /> <input type='submit' class='btn' value='post'></div>"

    ad="#comment-form"+e;
//    $(ad).css('width: 50%; display: block;');


    $(ad).css('width: 50%;');
    $(ad).html(ht);
    $(ad).toggle(100);
    if( $(ad).attr('ex')!='no')
        //$('textarea').remove('#cmt-area');
    //$(ad).show();

    $('#cmt-area').attr('cmt-id',e)

    if($(ad).attr('clicks')=='no'){
        $(ad).attr('clicks','yes')
        console.log('yes')
    }else {

        $(ad).attr('clicks','no')
        $('div').remove('#areas')
        console.log('no')
    }

    //$('#cmt-area').attr('cmt-id',e);

//    $('.comment-top').show("slide", { direction: "down" }, 1000);
    //$(ad).toggle(html)

    console.log("there");
    console.log(e)
}
/*$('#cmt').click(function(){
    alert('yess')
});*/



$(document).ready(function(){

    $('table').addClass('table')
    //console.log('hhh')
});
$(document).ready(function(){
    $('.table').removeAttr('style')
})


$(document).on('submit','#post-comment',function(e){
    e.preventDefault();
    console.log("skldflksdfj");
    $.ajax({
        type:'POST',
        url:'/community/comment/'+$('#cmt-area').attr('cmt-id'),
        data:{
            comment:$('#cmt-area').val(),
            csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
        },
        complete:function() {
            da=$('#cmt-area').val();
            console.log(da);
            ad='#comment-form'+$('#cmt-area').attr('cmt-id');
            $(ad).attr('clicks','no');
            //$('#comment-area').attr('clicks','no')
            temp=$('#cmt-area').val();

            $('div').remove('#areas');
            l="<p>"+temp+"</p><hr width='100' size='.5px' color='grey' align='left'>";
            console.log(l);
            //$('.comment-para').append(l).animate(200);
            //console.log(ad);
            $(ad).css('display','none')

        },
        success:function(e){
            console.log(e);
            if(e=='OK') {
                console.log('done');
                //$(ad).css('display','none')

            }else{
                //console.log(da)
            }

        }

    })
})

</script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en" style="font-family:GillSans, Calibri, Trebuchet, sans-serif;">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock title %}</title>

</head>
<body bgcolor="#dcdcdc">
{% include 'nav.html' %}
    {% block statics %}{% endblock %}
<br>
    <div class="container">
        {% block content %}{% endblock %}
        {% block sidebar %}{% endblock %}
    </div>
{% block script%}
{% endblock %}
</body>
</html>

templates/base2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock title %}</title>
</head>
<body bgcolor="#dcdcdc">
{% include 'nav.html' %}
<br>

{% block banner %}
{% endblock %}

<div class="container">
            {% block sidebar %}{% endblock %}
            {% block content %}
        {% endblock %}
    </div>
{% block script%}
{% endblock %}
</body>
</html>

templates/code.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col s12 m4 l12 icon-block">
            <div class="section no-pad-bot card-panel" id="index-banner">
            {% for i in c %}
                <div><a href="{{ i.id }}">
                <p class="orange-text">{{ i.code }} : {{ i.title }}</p></a>
                </div>
            {% endfor %}
            <br>
            </div>
        </div>
    </div>
{% endblock %}

templates/community.html
{% extends 'base2.html' %}
{% load staticfiles %}
{% block title %} Community {% endblock %}
<link rel="stylesheet" href="{% static 'materialize/css/materialize.min.css' %}">
<link rel="stylesheet" href="{% static 'style.css' %}">

{% block banner %}
<div class="center parallax-container card-panel">
    <div class="section no-pad-bot center">
      <div class="container valign">
        <br><br>
        <h1 class="header center grey-text text-darken-2">Join Community</h1>
        <div class="row center">
          <h5 class="header col s12 light grey-text text-darken-2">Join ignouz community and ask questions</h5>
        </div>
        <div class="row center">
          <a href="#startPosts" class="btn-floating btn-large waves-effect waves-light grey darken-2 head-link"><i class="fa fa-angle-double-down"></i></a>
        </div>
        <br><br>
      </div>
    </div></div>
{% endblock %}
{% block content %}

    {% for i in com %}
        <div class="row">
        <a href="{{ i }}/">
            <div class="col s12 m5 l12 icon-block">
                <div class="section no-pad-bot card-panel" id="index-banner">
                        <div class="row">
                        <h5>{{ i.qs }}</h5>
                          <br><br>
                    </div>
            </div>
        </a>
    {% endfor %}
{% endblock %}

templates/css.html
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'materialize/css/materialize.min.css' %}">
<link rel="stylesheet" href="{% static 'css/materialNote.css' %}">
<link rel="stylesheet" href="{% static 'style.css' %}">

templates/editor_file.html
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'ckeditor/ckeditor.js' %}"></script>
<script src="{% static 'ckeditor/samples/js/sample.js' %}"></script>
<link rel="stylesheet" href="{% static 'ckeditor/samples/css/samples.css' %}">
<link rel="stylesheet" href="{% static 'ckeditor/samples/toolbarconfigurator/lib/codemirror/neo.css' %}">



<!--<script src="{% static 'materialize/js/materialize.min.js' %}"></script>
<script src="{% static 'js/ckMaterializeOverrides.js' %}"></script>
<script src="{% static 'lib/codeMirror/xml.js' %}"></script>
<script src="{% static 'js/materialNote.js' %}"></script>
<link rel="stylesheet" href="{% static 'style.css' %}">
<link rel="stylesheet" href="{% static 'materialize/css/materialize.min.css' %}">
<link rel="stylesheet" href="{% static 'css/materialNote.css' %}">
<link rel="stylesheet" href="{% static 'css/codeMirror/codemirror.css' %}">
<link rel="stylesheet" href="{% static 'css/codeMirror/monokai.css' %}">-->

templates/give_answer.html
{% extends 'base.html' %}
{% block content %}
<nav class="navigation-a">
	<div class="grid-container">
		<ul class="navigation-a-left grid-width-70">
			<li><a href="http://ckeditor.com">Project Homepage</a></li>
			<li><a href="http://dev.ckeditor.com/">I found a bug</a></li>
			<li><a href="http://github.com/ckeditor/ckeditor-dev" class="icon-pos-right icon-navigation-a-github">Fork CKEditor on GitHub</a></li>
		</ul>
		<ul class="navigation-a-right grid-width-30">
			<li><a href="http://ckeditor.com/blog-list">CKEditor Blog</a></li>
		</ul>
	</div>
</nav>

<header class="header-a">
	<div class="grid-container">
		<h1 class="header-a-logo grid-width-30">
			<a href="index.html"><img src="img/logo.png" alt="CKEditor Sample"></a>
		</h1>

		<nav class="navigation-b grid-width-70">
			<ul>
				<li><a href="index.html" class="button-a button-a-background">Start</a></li>
				<li><a href="toolbarconfigurator/index.html" class="button-a">Toolbar configurator <span class="balloon-a balloon-a-nw">Edit your toolbar now!</span></a></li>
			</ul>
		</nav>
	</div>
</header>

<main>
	<div class="adjoined-top">
		<div class="grid-container">
			<div class="content grid-width-100">
				<h1>Congratulations!</h1>
				<p>
					If you can see CKEditor below, it means that the installation succeeded.
					You can now try out your new editor version, see its features, and when you are ready to move on, check some of the <a href="#sample-customize">most useful resources</a> recommended below.
				</p>
			</div>
		</div>
	</div>
	<div class="adjoined-bottom">
		<div class="grid-container">
			<div class="grid-width-100">
				<div id="editor">
					<h1>Hello world!</h1>
					<p>I'm an instance of <a href="http://ckeditor.com">CKEditor</a>.</p>
				</div>
			</div>
		</div>
	</div>

	<div class="grid-container">
		<div class="content grid-width-100">
			<section id="sample-customize">
				<h2>Customize Your Editor</h2>
				<p>Modular build and <a href="http://docs.ckeditor.com/#!/guide/dev_configuration">numerous configuration options</a> give you nearly endless possibilities to customize CKEditor. Replace the content of your <code><a href="../config.js">config.js</a></code> file with the following code and refresh this page (<strong>remember to clear the browser cache</strong>)!</p>
		<pre class="cm-s-neo CodeMirror"><code><span style="padding-right: 0.1px;"><span class="cm-variable">CKEDITOR</span>.<span class="cm-property">editorConfig</span> <span class="cm-operator">=</span> <span class="cm-keyword">function</span>( <span class="cm-def">config</span> ) {</span>
<span style="padding-right: 0.1px;"><span class="cm-tab">	</span><span class="cm-variable-2">config</span>.<span class="cm-property">language</span> <span class="cm-operator">=</span> <span class="cm-string">'es'</span>;</span>
<span style="padding-right: 0.1px;"><span class="cm-tab">	</span><span class="cm-variable-2">config</span>.<span class="cm-property">uiColor</span> <span class="cm-operator">=</span> <span class="cm-string">'#F7B42C'</span>;</span>
<span style="padding-right: 0.1px;"><span class="cm-tab">	</span><span class="cm-variable-2">config</span>.<span class="cm-property">height</span> <span class="cm-operator">=</span> <span class="cm-number">300</span>;</span>
<span style="padding-right: 0.1px;"><span class="cm-tab">	</span><span class="cm-variable-2">config</span>.<span class="cm-property">toolbarCanCollapse</span> <span class="cm-operator">=</span> <span class="cm-atom">true</span>;</span>
<span style="padding-right: 0.1px;">};</span></code></pre>
			</section>

			<section>
				<h2>Toolbar Configuration</h2>
				<p>If you want to reorder toolbar buttons or remove some of them, check <a href="toolbarconfigurator/index.html">this handy tool</a>!</p>
			</section>

			<section>
				<h2>More Samples!</h2>
				<p>Visit the <a href="http://sdk.ckeditor.com">CKEditor SDK</a> for a huge collection of samples showcasing editor features, with source code readily available to copy and use in your own implementation.</p>
			</section>

			<section>
				<h2>Developer's Guide</h2>
				<p>The most important resource for all developers working with CKEditor, integrating it with their websites and applications, and customizing to their needs. You can start from here:</p>
				<ul>
					<li><a href="http://docs.ckeditor.com/#!/guide/dev_installation">Getting Started</a> &ndash; Explains most crucial editor concepts and practices as well as the installation process and integration with your website.</li>
					<li><a href="http://docs.ckeditor.com/#!/guide/dev_advanced_installation">Advanced Installation Concepts</a> &ndash; Describes how to upgrade, install additional components (plugins, skins), or create a custom build.</li>
				</ul>
					<p>When you have the basics sorted out, feel free to browse some more advanced sections like:</p>
				<ul>
					<li><a href="http://docs.ckeditor.com/#!/guide/dev_features">Functionality Overview</a> &ndash; Descriptions and samples of various editor features.</li>
					<li><a href="http://docs.ckeditor.com/#!/guide/plugin_sdk_intro">Plugin SDK</a>, <a href="http://docs.ckeditor.com/#!/guide/widget_sdk_intro">Widget SDK</a>, and <a href="http://docs.ckeditor.com/#!/guide/skin_sdk_intro">Skin SDK</a> &ndash; Useful when you want to create your own editor components.</li>
				</ul>
			</section>

			<section>
				<h2>CKEditor JavaScript API</h2>
				<p>CKEditor boasts a rich <a href="http://docs.ckeditor.com/#!/api">JavaScript API</a> that you can use to adjust the editor to your needs and integrate it with your website or application.</p>
			</section>
		</div>
	</div>
</main>

<footer class="footer-a grid-container">
	<div class="grid-container">
		<p class="grid-width-100">
			CKEditor &ndash; The text editor for the Internet &ndash; <a class="samples" href="http://ckeditor.com/">http://ckeditor.com</a>
		</p>
		<p class="grid-width-100" id="copy">
			Copyright &copy; 2003-2017, <a class="samples" href="http://cksource.com/">CKSource</a> &ndash; Frederico Knabben. All rights reserved.
		</p>
	</div>
</footer>
<script>
	initSample();
</script>
{% endblock %}

templates/grade.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <title>Grade Card</title>
    {% include 'nav.html' %}

    <div class="container">
        {% csrf_token %}
        <form id="frm" name="frm" action="/result/" method="get">

            <div class="row">
                <div class="col s9 m4 l3">
                    <input type="text" class="form-control" name="enrol" id="enrol" placeholder="Enrolment No">
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12 m4 l3">
                <input type="text" class="form-control" name="Program" placeholder="Program" id="program">
                </div>
                <div class="col s9 m4 l3">
                   <input type="submit" class="btn btn-primary" name="btn" value="submit">
                   <input value="ok" name="hidden_submit" type="hidden">
                </div>
            </div>
<!--            <div class="row">
                <iframe src="http://admission.ignou.ac.in/changeadmdata/admissionstatusnew.asp"   frameBorder="0" scrolling="no" style="margin-left: 7px; margin-bottom:-220px; margin-top: 0px;height: 1500px;  width: 100%">
                <div id="results">-->
        </form>
    </div>
</head>
<body>

<!--<script type="text/javascript">
    //$('#results').load('https://webservices.ignou.ac.in/GradecardM/?Program=BCA&eno=126976835&submit=Submit&hidden_submit=OK');
    $(document).on('submit','#frm',function (e) {
        e.preventDefault()
        $.ajax({
            type:'GET',
            //url : '/',
            crossOrigin: true,
            crossDomain: true,

            url : 'https://webservices.ignou.ac.in/GradecardM/',
            data:{
                Program:$('#program').val(),
                eno:$('#enrol').val(),
                submit:"Submit",
                hidden_submit:"OK"
            },
            success:function (e) {
                //console.log("success");
                //alert("Sucsess");
                $('#results').html(e)
            },
            error: function(err) {
           console.log(err);
        }
        })
    });
</script>-->

</body>
</html>

templates/js.html
{% load staticfiles %}
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'materialize/js/materialize.min.js' %}"></script>

templates/nav.html
{% load staticfiles %}

<!--<link rel="stylesheet" href={% static 'materialize/css/materialize.css' %}>
<script src="{% static 'js/jquery.js' %}"></script>
<!--<link rel="stylesheet" href="{% static 'style.css' %}">-->
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<!--<script src="{% static 'materialize/js/materialize.js' %}"></script>
<script src="{% static 'js/waves.js' %}"></script>-->
{% include 'js.html' %}
{% include 'css.html' %}
<nav class="light-blue lighten-1" role="navigation">
    <div class="nav-wrapper container navbar-fixed">
        <a id="logo-container" href="/" class="brand-logo center"><img src="{% static 'logo/ignou.png' %}" width="60"></a>
       <ul class=" right hide-on-med-and-down">
           <li><a href="#" >Profile</a></li>
           {% if user.username %}
           <li><a href="accounts/logout" >Logout</a></li>
           {% else %}
           <li><a href="accounts/login" >Login</a></li>
            {% endif %}
           <li><a href="#">{{ user.username }} </a> </li>
      </ul>
      <ul class="left hide-on-med-and-down">
          <li><a href="#"> ABC</a></li>
          <li><a href="#"> XYZ </a></li>
      </ul>
      <ul id="nav-mobile" class="side-nav">
        <li><a href="#">Navbar Link</a></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse "><i class="material-icons ">menu</i></a>
    </div>
</nav>
<br>

templates/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Result</title>
</head>
<body>
{% include 'nav.html'%}
    <div class="container">
        <div class="row">
        <div class="col s12 m4 l7">
            {% for i in info %}
            <h5>{{ i }}</h5>
            {% endfor %}
            <h5 id="h5">Total Percentage : </h5>
        </div>
        </div>
        <div class="row">
            <div class="col s9 m4 l5">
                <table class="responsive-table">
                    {% for i in mark %}
                        <tr>
                        {% for j in i %}
                            {% if j == "Not Completed" %}
                            <td align="center" class="num" style="color: red">{{ j }}</td>
                            {% elif j == "Completed" %}
                            <td align="center" class="num" style="color: Green">{{ j }}</td>
                            {% else %}
                             <td align="center" class="num">{{ j }}</td>

                            {% endif%}
                        {% endfor %}
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>

<script type="text/javascript">
/*var input = $('.num');
    for(var i=0;i<input.length;i++){
        console.log($(input[i]).val())
    }
    $('.num').each(function () {
        console.log(this.value)
    })*/
    $(".num").each(function() {
        console.log($(this).text().serialize());
    });
    //console.log($('.num').serialize())
    console.log("righ")
</script>
</body>
</html>